/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinationprogramme;

import javax.swing.JOptionPane;

/**
 * VaccinationProgrammeGUI.java
 * @author Aaron
 * 27/03/2021
 */
public class VaccinationProgrammeGUI extends javax.swing.JFrame {

    /**
     * Creates new form VaccinationProgrammeGUI
     */
    private PQInterface myPQueue;
    public VaccinationProgrammeGUI() {
        myPQueue = new MyPriorityQueue();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJLabel = new javax.swing.JLabel();
        addBorderJPanel = new javax.swing.JPanel();
        nameJLabel = new javax.swing.JLabel();
        ageJLabel = new javax.swing.JLabel();
        conditionJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        ageJTextField = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();
        conditionJTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaDisplay = new javax.swing.JTextArea();
        listJButton = new javax.swing.JButton();
        numRecJButton = new javax.swing.JButton();
        scheduledJButton = new javax.swing.JButton();
        exitJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerJLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        headerJLabel.setText("Covid-19 Vaccination Programme");

        addBorderJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Recipient"));

        nameJLabel.setText("Person's Name: ");

        ageJLabel.setText("Person's Age: ");

        conditionJLabel.setText("Medical Condition (y/n):");

        ageJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageJTextFieldActionPerformed(evt);
            }
        });

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        conditionJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conditionJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addBorderJPanelLayout = new javax.swing.GroupLayout(addBorderJPanel);
        addBorderJPanel.setLayout(addBorderJPanelLayout);
        addBorderJPanelLayout.setHorizontalGroup(
            addBorderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBorderJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addBorderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addBorderJPanelLayout.createSequentialGroup()
                        .addComponent(conditionJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(conditionJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                    .addGroup(addBorderJPanelLayout.createSequentialGroup()
                        .addGroup(addBorderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameJLabel)
                            .addComponent(ageJLabel))
                        .addGap(55, 55, 55)
                        .addGroup(addBorderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ageJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(nameJTextField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addBorderJPanelLayout.setVerticalGroup(
            addBorderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBorderJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addBorderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJLabel)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addJButton))
                .addGap(10, 10, 10)
                .addGroup(addBorderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageJLabel)
                    .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addBorderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conditionJLabel)
                    .addComponent(conditionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recipients to be Vaccinated"));

        jTextAreaDisplay.setColumns(20);
        jTextAreaDisplay.setRows(5);
        jScrollPane.setViewportView(jTextAreaDisplay);

        listJButton.setText("List");
        listJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listJButtonActionPerformed(evt);
            }
        });

        numRecJButton.setText("Number of Recipients");
        numRecJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numRecJButtonActionPerformed(evt);
            }
        });

        scheduledJButton.setText("Next Group to be Scheduled for the vaccine");
        scheduledJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduledJButtonActionPerformed(evt);
            }
        });

        exitJButton.setText("Exit");
        exitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numRecJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scheduledJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(listJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numRecJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scheduledJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitJButton)
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addComponent(jScrollPane))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addBorderJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(headerJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(headerJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBorderJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageJTextFieldActionPerformed

    private void listJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listJButtonActionPerformed
        // TODO add your handling code here:
        jTextAreaDisplay.append("The patients awaiting the vaccine are listed below.\n");
        jTextAreaDisplay.append(myPQueue.printPQueue()+ "\n");
    }//GEN-LAST:event_listJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        // Local variables
        String name, condition;
        int age, priority = 0;

        // Accept new Vaccination Recipients
        VaccinationRecipients r = new VaccinationRecipients();
        // Take name put into nameJTextField and store it in name
        name = nameJTextField.getText();
        // Error Handling
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Name is empty, please enter your name.");
            System.exit(0);
        }
  
        // Take age from ageJTextField and put it into the age variable
        age = Integer.parseInt(ageJTextField.getText());
        
        // Checking whether the recipient has a medical condition or not
        condition = conditionJTextField.getText();
        
        // Error Handling
        if(!condition.equalsIgnoreCase("y") && !condition.equalsIgnoreCase("n")){
            JOptionPane.showMessageDialog(null, "You have entered an incorrect medical condition, either enter y for yes or n for no");
            System.exit(0);
        }
            
        // Setting Values
        r.setName(name);
        r.setAge(age);
        r.setCondition(condition);
        
        // Automatically assigning a priority to the person that was added
        if(age >= 0){
            if(age >= 90){
                priority = 10;  
            }
            else if(age >= 80){
                priority = 9;  
               
            }
            else if(age >= 70){
                priority = 8;  
                
            }
             else if(age >= 65){
                priority = 7;  
                
            }
             
            else if(age >= 18 && age <= 64 && (condition.equalsIgnoreCase("y"))){       
                priority = 6;  
            }
             
            else if(age >= 55){
                priority = 5;  
                
                
            }
            else if(age >= 45){
                priority = 4;  
                
            }
            else if(age >= 30){
                priority = 3;  
                
            }  
            else if(age >= 18){
                priority = 2;  
                
            }        
            else{
                priority = 1;  
            }    
        }
        
        // Add an element to the queue
        myPQueue.enqueue(priority,r);
        
        // Display that the user input has been accepted and output
        jTextAreaDisplay.append(nameJTextField.getText() + ", your information has successfully been added to the queue" + "\n");
        nameJTextField.setText("");
        ageJTextField.setText("");
        conditionJTextField.setText("");
        
        
    }//GEN-LAST:event_addJButtonActionPerformed

    private void conditionJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conditionJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conditionJTextFieldActionPerformed

    private void numRecJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numRecJButtonActionPerformed
        // TODO add your handling code here:
        jTextAreaDisplay.append("There are " + myPQueue.size() + " patients awaiting a vaccine in the queue" + "\n");
    }//GEN-LAST:event_numRecJButtonActionPerformed

    private void exitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitJButtonActionPerformed

    private void scheduledJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduledJButtonActionPerformed
        // TODO add your handling code here:
        
        if(!myPQueue.isEmpty()){
            PQElement pqelem = (PQElement)myPQueue.dequeue();
            VaccinationRecipients vr1 = (VaccinationRecipients)pqelem.getElement();  
                            
            jTextAreaDisplay.append("The Following will be vaccinated tomorrow " + vr1.getName());
        }

        else{
            jTextAreaDisplay.append("There are no more patients waiting"+ "\n");
        }
        
        

    }//GEN-LAST:event_scheduledJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VaccinationProgrammeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VaccinationProgrammeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VaccinationProgrammeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VaccinationProgrammeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VaccinationProgrammeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBorderJPanel;
    private javax.swing.JButton addJButton;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JLabel conditionJLabel;
    private javax.swing.JTextField conditionJTextField;
    private javax.swing.JButton exitJButton;
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextAreaDisplay;
    private javax.swing.JButton listJButton;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton numRecJButton;
    private javax.swing.JButton scheduledJButton;
    // End of variables declaration//GEN-END:variables
}
